### ISSUE TITLE
Docs feedback.

### ISSUE THREAD

**Issue by AntonAndell** [icon-project/centralized-relay#97]
From initial setup i got a few points of feedback:

- On Installation steps  it should be clear it is a OR 1 then 2 feels like you are supposed to do both.
- The actual name of the CLI is centralied-relay and not crly, can be renamed for start or during the move step. Also move step depends on installation method. 
- No guide to deploy contracts, might be useful to give a example of deploying the contracts for each chain type. 
- Start height explanation in cfg, 0 means from latest i would assume?
- What is concurrency in EVM?
- Why no password on ICON?
- For the configs display and explain all possible values.
- Test configs and commands are not the same, mumbai then fuji for other steps. Would be easier to follow if done for same chains all through setup. 
- Example config for EVM has a ICON contract address

**Comment by AntonAndell** [comment]
To add the docs in general looks and feels great, Good work! This is a product that could become really good as we keep developing it

**Comment by debendraoli** [comment]
> Why no password on ICON?

There is password for icon too, password is not actually used on configuration rather encrypted when creating or importing and saved as file which is automatically restored when starting.

**Comment by bishalbikram** [comment]
Here i got few feedback during installation:

**Installation step 1:**
1. make install
- After `make install` centralized-relay command is not directly available as shell-command
- After `make install`, 'go' directory is created in home directory of user. it includes bin directory and inside bin directory we have "crly" executable binary
- Executing `sudo mv ~/go/bin/crly /usr/local/bin` command allows to execute `crly` as shell-command

2. keystore
- Doc mentions to use "create" command in order to create new keystore. But "new" is being used to create keystore
- Password flag is required to execute `crly keystore use` but not mentioned in the doc
- When using `crly keystore use` with password flag, it throws an error message: "Error: unknown flag: --password"

**Installation step 2:**
- Invalid filename "tar -xvf centralized-relay_0.0.1-alpha4_linux_amd64.tar.gz". correct file name -> "centralised-relay_0.0.1-alpha4_linux_amd64.tar.gz"

General
- "centralized-relay" & "crly" is not consistently being used in installation and docs

**Comment by CyrusVorwald** [comment]
One thing to add - it isn't clear that this is using xcall or how messages are passed, unless I am missing something.

**Comment by debendraoli** [comment]
> One thing to add - it isn't clear that this is using xcall or how messages are passed, unless I am missing something.

Can you elaborate more on this?

We are not using xcall to pass message between chains rather receiveMessage method of connection contract to pass messages between chains.

**Comment by pragyanshrestha-ibriz** [comment]
https://github.com/icon-project/centralized-relay/pull/134
